name: em_repairs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  barcode_scan2: ^4.3.3
  intl: ^0.20.1
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.3.5
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  path: ^1.9.0
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  flutter_launcher_icons: ^0.14.2
  sqflite: ^2.4.1
  google_sign_in: ^6.2.2
  appwrite: ^13.1.1
  get_it: ^8.0.3
  internet_connection_checker: ^3.0.1
  provider: ^6.1.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"
